-- https://school.programmers.co.kr/learn/courses/30/lessons/131123
-- 즐겨찾기가 가장 많은 식당 정보 출력하기

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R
    LEFT JOIN (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) AS T ON T.FOOD_TYPE = R.FOOD_TYPE
WHERE T.FAVORITES = R.FAVORITES
ORDER BY R.FOOD_TYPE DESC