-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
-- 상품 별 오프라인 매출 구하기

SELECT PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
    LEFT JOIN OFFLINE_SALE AS O ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY 2 DESC,1