-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
-- 성분으로 구분한 아이스크림 총 주문량

SELECT I.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F
    LEFT JOIN ICECREAM_INFO AS I ON I.FLAVOR = F.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY 2